### ISSUE TITLE
Can't add non-string default in optional value

### ISSUE THREAD

**Issue by delenius** [simkoc/scala-argparse#7]
The method `addOptional` takes an argument `default: Option[String] = None`.
It seems this should be Option[T], so that we can use e.g., an `Int` default value.

**Comment by simkoc** [comment]
Yes, that is a great suggestion. I will probably work on an update for the package within the coming weeks.

**Comment by simkoc** [comment]
I made the whole API type flexible starting with `2.0.0`, you can (currently have to) provide a parser argument that turns the string cmd line value into the type you want. This also means that optionals can now have directly the value you want.
