### ISSUE TITLE
Add support for scala 2.12

### ISSUE THREAD

**Issue by fjellvannet** [simkoc/scala-argparse#8]
Spark claims to be compatible with scala 2.13 since spark 3.2, however trying to run this library on AWS with spark 3.4.1, a lot of errors are produced, indicating that the code won't run in scala 2.12. 

To make this code run in scala 2.12, only a few simple substitutions need to be made in the code. I have that code ready if you would like to take a look.

It won't work to make the code 2.12 and 2.13 compatible at the same time, but probably a sister-version could be created which can be downloaded for scala 2.12?

**Comment by fjellvannet** [comment]
I wanted to post my code here on a separate branch, but as far as I can see it I'm not allowed to create a branch or push new code as of now.

**Comment by simkoc** [comment]
if it is not possible to be both scala 2.12 and 2.13 compatible at once I would suggest you just fork the repository and apply your required changes.

**Comment by simkoc** [comment]
I released version `2.0.1`  today, which improved the interface to get the values that have been parsed from the command line. Starting with this version `2.12`  is now a release candidate as well. I also tried to do `2.11` but the code incompatibilities are too big to be feasible or worth it for me.
